BEGIN TRANSACTION;


INSERT INTO users (username,password_hash,role) VALUES ('Brian','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_LANDLORD');
INSERT INTO users (username,password_hash,role) VALUES ('Dan','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_LANDLORD');
INSERT INTO users (username,password_hash,role) VALUES ('Eric','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_LANDLORD');
INSERT INTO users (username,password_hash,role) VALUES ('Ethan','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_LANDLORD');
INSERT INTO users (username,password_hash,role) VALUES ('renter1','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_RENTER');
INSERT INTO users (username,password_hash,role) VALUES ('renter2','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_RENTER');
INSERT INTO users (username,password_hash,role) VALUES ('renter3','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_RENTER');
INSERT INTO users (username,password_hash,role) VALUES ('renter4','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_RENTER');
INSERT INTO users (username,password_hash,role) VALUES ('renter5','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_RENTER');
INSERT INTO users (username,password_hash,role) VALUES ('renter6','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_RENTER');
INSERT INTO users (username,password_hash,role) VALUES ('renter7','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_RENTER');
INSERT INTO users (username,password_hash,role) VALUES ('renter8','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_RENTER');



INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('3837 Ackley Wy, Pittsburgh, PA 15214', 1680.00, 1.5, 2, true, 'house', 'Located in the historic north side area of Pittsburgh. This cozy 2-Bed, 1.5-Bath home is equipped with its luxurious furnishings, a full kitchen, dining room, movie theatre, Wi-Fi, parking, smart locks for your safety and much more. Treat your taste buds at the north-shore 9 minutes away from this home. That’s just a teaser, looking to dig deeper check out the overlook in the west end with sensational views of the shimmering skyline. Be sure to spend a night out on the southside for bars & clubs.', 'https://a0.muscache.com/im/pictures/miso/Hosting-649102397892688083/original/279b62ec-971a-4068-87cb-688f4103204a.jpeg?aki_policy=large', 3);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('2318 Jane St, Pittsburgh, PA 15203', 1950.00, 2.5, 3, true, 'house', 'Kick back and relax in this calm, stylish space. Our house has 3 bedrooms available on the second floor of the house. We have kings size bed in the master bedroom, queen size bed and full size bed in the third bedroom. A portable baby crib is available for use if needed. The house has 2 full bathrooms and 1 half bath.', 'https://a0.muscache.com/im/pictures/miso/Hosting-673696039027617516/original/fdeada62-422f-44e2-8d63-968f082f611c.png?aki_policy=large', 3);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('36 Enon Way, Pittsburgh, PA 15203', 910.00, 1.0, 1, false, 'apartment', 'Updated 1 bedroom apartment just a couple blocks from South Side Flats entertainment district. Close to everything, yet secluded from the hustle and bustle of Carson street, downtown, and Oakland. The bedroom includes a queen-sized bed. Wifi is included.', 'https://a0.muscache.com/im/pictures/miso/Hosting-38729034/original/413494dd-dfcb-4149-aad0-f02552e29fcc.jpeg?aki_policy=small', 3);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('319 Sweetbriar St, Pittsburgh, PA 15211', 1650.00, 1.0, 3, false, 'house', 'Keep it simple at this peaceful and centrally-located 3-Bedroom home. Located just one block from the famous Mt. Washington overlook, this home is conveniently located to everything Pittsburgh has to offer. Features a spacious backyard, high-speed WIFI, SmartTV, laundry facilities, memory-foam beds and plenty of FREE street parking! Close to groceries, restaurants, hiking trails, and just a short ride down the iconic Pittsburgh Incline to reach Downtown, South-Side, and Station Square.', 'https://a0.muscache.com/im/pictures/miso/Hosting-660635555742898325/original/e8d2c4d1-472d-4746-a608-37fdf1e9fb6a.jpeg?aki_policy=small', 3);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('209 9th St Apartment 1, Pittsburgh, PA 15222', 590.00, 1.0, 1.0, true, 'apartment', 'All Front desk stays are contactless self-check-in and include Scout, our exclusive digital companion to guide you through everything you will need before and during your time with us. We are also available 24/7 via text or phone and have a local team should you need anything.', 'https://a0.muscache.com/im/pictures/prohost-api/Hosting-645540054560482356/original/061b19ab-90f2-48e3-9cd8-8fbbe4b726ab.jpeg?aki_policy=small', 4);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('209 9th St Apartment 2, Pittsburgh, PA 15222', 590.00, 1.0, 1.0, true, 'apartment', 'Please note, the building is currently undergoing a complete renovation, including the lobby, entrance/exit areas, common areas, hallways, etc. and there are active construction sites that guests will have to pass through during their stay.', 'https://a0.muscache.com/im/pictures/prohost-api/Hosting-659446227161633075/original/f31841f8-01f1-4522-9a2b-028f45f7d107.jpeg?aki_policy=large', 4);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('5606 Stanton Ave Apartment 3, Pittsburgh, PA 15206', 590.00, 1.0, 1.0, false, 'apartment', 'Anything in the apartment is yours to use. Make yourself at home once you arrive. While traditional cable TV is not included in your stay, we do provide Roku TVs with apps like Netflix, Prime, Hulu, and more! Feel free to use these services with your own login and enjoy!', 'https://a0.muscache.com/im/pictures/prohost-api/Hosting-645713686230889645/original/8dba2fe3-db8c-45a3-bbd0-db451c1b6c37.jpeg?aki_policy=large', 3);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('5606 Stanton Ave Apartment 6, Pittsburgh, PA 15206', 590.00, 1.0, 1.0, false, 'apartment', 'All Frontdesk stays are contactless self-check-in and include Scout, our exclusive digital companion to guide you through everything you will need before and during your time with us. We are also available 24/7 via text or phone and have a local team should you need anything.', 'https://a0.muscache.com/im/pictures/prohost-api/Hosting-659225921537019795/original/a4fcf0a8-d4af-4f42-a01a-be4ad13ce7af.jpeg?aki_policy=large', 3);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('5606 Stanton Ave Apartment 9, Pittsburgh, PA 15206', 590.00, 1.0, 1.0, false, 'apartment', 'Spacious Basement suite in my home with full sized bed , electric fireplace, treadmill workout area, work desk, mini microwave kitchenette, 42" flat screen TV, Wi-Fi, bathroom/ shower, laundry facilities and off street parking. Room is tastefully decorated warm, inviting and functional. Guest uses garage entrance with code, 100% privacy. Host may be on property. 8 Minutes from downtown, PNC Park, Heinz Field, Pittsburgh Paints Arena, Mt Washingtons Inclines and restaurants 15 from Airport A full sized bed and fireplace will greet you.', 'https://a0.muscache.com/im/pictures/miso/Hosting-667490516860790612/original/1e046a79-f964-434c-8a7d-16370620b247.jpeg?aki_policy=large', 3);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('5606 Stanton Ave Apartment 1, Pittsburgh, PA 15206', 380.00, 1.0, 1.0, false, 'apartment', 'Stanton Castle is located in the vibrant East End of Pittsburgh. The private room is located in the third floor apartment. There are three locked bedrooms in the apartment, each with their own private bathrooms. The kitchen and lounge are shared with other guests like yourself.','https://a0.muscache.com/im/pictures/miso/Hosting-17944234/original/4ec25eff-06ed-4d4d-9204-b4302414ffdf.jpeg?aki_policy=large', 3);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('925 unfair Street, Pittsburgh, Pa 15237', 1250.00, 1.5, 3, false, 'apartment', 'Welcome to the Zen Den in the the Woodbridge. While you are only approximately 8 miles from the city and centrally located to shopping, theatre, sports, and river - you feel nestled in a woodsy retreat to tap into the zen each evening. 3 stories and 3 bedrooms give this townhouse plenty of room to spread out. 1 full bath + 1 half bath and a spacious updated kitchen will all the amenities. Enjoy the community pool in the summer and nice walks to keep the mind at peace., ', 'https://a0.muscache.com/im/pictures/miso/Hosting-685401776224888208/original/71649ad4-0cb0-458c-b99d-5cc0409662b7.jpeg?aki_policy=x_large', 3);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('140 prerequires Street, Pittsburgh, Pa 15211', 1990.00, 1.5, 5, false, 'apartment', 'Please be respectful of the guests behind you and our neighbors.  We ask that you observe quiet hours between 10pm and 8am. Please consider this before booking this Airbnb., ', 'https://a0.muscache.com/im/pictures/miso/Hosting-686024964669745796/original/223040d4-c226-497a-bbdc-b2bb7a2868d2.jpeg?aki_policy=x_large', 3);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('33 synchronise Street, Pittsburgh, Pa 15221', 890.00, 1, 1, false, 'apartment', 'Pets are welcome for a one time fee of $65., ', 'https://a0.muscache.com/im/pictures/8a502ff5-5dc1-4578-8af6-13d13ada64bd.jpg?aki_policy=x_large', 3);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('304 gropers Street, Pittsburgh, Pa 15212', 1100.00, 1, 2, true, 'apartment', 'Contact availability 24/7 from Host, ', 'https://a0.muscache.com/im/pictures/miso/Hosting-686776783911117800/original/57179c65-5a0c-47de-82c0-2971e5aa290e.jpeg?aki_policy=x_large', 1);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('695 mump Street, Pittsburgh, Pa 15228', 1800.00, 2, 2, false, 'apartment', 'Located in Brighton Heights this quaint home is located in a quiet neighborhood in North Pittsburgh, yet still close to all downtown has to offer. Just an 8 min drive from Heinz Field & PNC park and 12 minutes to downtown. Conveniently located, this home is perfect choice for your Pittsburgh vacation., ', 'https://a0.muscache.com/im/pictures/miso/Hosting-608534997479078572/original/339761b9-5881-47b6-91d1-392e1ba9a710.jpeg?aki_policy=x_large', 3);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('392 opulent Street, Pittsburgh, Pa 15222', 590.00, 1, 1, true, 'apartment', 'Lock Box on front porch, ', 'https://a0.muscache.com/im/pictures/prohost-api/Hosting-681165957466969792/original/add449ac-2820-4892-b7b0-89e6f349b263.jpeg?aki_policy=x_large', 1);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('552 tablespoonfuls Street, Pittsburgh, Pa 15224', 970.00, 1, 1, true, 'apartment', 'Steps away from Uptown Mt. Lebanon restaurants and shops., ', 'https://a0.muscache.com/im/pictures/miso/Hosting-551274712241055453/original/939835e4-5b3d-40b3-a05d-a7e676405bee.jpeg?aki_policy=x_large', 1);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('964 wimps Street, Pittsburgh, Pa 15203', 2000.00, 2, 3, true, 'apartment', 'At Frontdesk, a core value is to be a good neighbor. We extend this 5-star stay to you, our guests, as well as our property partners. This means we have a zero-tolerance policy for parties or gatherings. To ensure this in the most comfortable and least intrusive way possible, we use a noise sensor to detect the noise level inside of the suite. The number of people inside the suite may not exceed the reserved guest amount at any time. While we do not anticipate the need, following multiple warnings, we will utilize local law enforcement to ensure compliance. If removal is required, it will be done at the guests expense.  Thank you for respecting the community and our commitment to be a good neighbor., ', 'https://a0.muscache.com/im/pictures/prohost-api/Hosting-671504497959197333/original/abe74fec-a88b-4096-865c-98f69f78f131.jpeg?aki_policy=x_large', 2);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('534 silverpoint Street, Pittsburgh, Pa 15241', 1890.00, 1, 3, false, 'apartment', 'Plenty of street parking, ', 'https://a0.muscache.com/im/pictures/miso/Hosting-683315005023671601/original/46144d7c-1137-4d25-80d1-6bb2623d3148.jpeg?aki_policy=x_large', 2);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('10 applet Street, Pittsburgh, Pa 15218', 890.00, 1, 1, false, 'apartment', 'Walk, drive and/or uber!, ', 'https://a0.muscache.com/im/pictures/miso/Hosting-683305254586189134/original/b781c281-fb0d-4b63-a07f-d11809c1bacf.jpeg?aki_policy=x_large', 1);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('284 coffees Street, Pittsburgh, Pa 15221', 1690.00, 1, 3, false, 'apartment', 'This stylish place to stay is perfect for group trips. Themed around music and vintage artwork, this fashionable home is centered around good vibes. With a one minute drive to route 19, you’ll find countless restaurants, bars, entertainment venues along with the south hills village mall! Ride-shares and Public transportation are abundant and will take you directly to downtown pittsburgh and the north shore for sporting events, family fun, and much more. Less than 30 minutes to Airport & DT 🏙✨, ', 'https://a0.muscache.com/im/pictures/miso/Hosting-681724948207177824/original/34c8662b-73d5-4843-82c4-15b8d3336103.jpeg?aki_policy=x_large', 1);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('567 retacks Street, Pittsburgh, Pa 15219', 1990.00, 1, 1, false, 'apartment', 'You can walk to most places. There is a nearby bus stop if you dont have a car., ', 'https://a0.muscache.com/im/pictures/fc9e7ad0-2ad3-4b09-b6a5-d006ffddd65e.jpg?aki_policy=x_large', 3);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('315 rawin Street, Pittsburgh, Pa 15210', 2040.00, 2, 3, false, 'apartment', 'We offer free on street parking! If you are in need of a ride Uber is available ✨, ', 'https://a0.muscache.com/im/pictures/miso/Hosting-659426559829010396/original/f41179ce-a2e0-47c9-af83-a665e9dcdfac.png?aki_policy=x_large', 3);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('876 teethridge Street, Pittsburgh, Pa 15213', 730.00, 1.5, 1, false, 'apartment', 'You cant beat the walkability from here. Pittsburgh is a notoriously difficult city to drive in, so the easiest solution is to walk, ride one of the bike sharing programs, Spin scooters, or jump in an Uber / Lyft., ', 'https://a0.muscache.com/im/pictures/72c24c73-bef2-4c62-b026-d645a97c511e.jpg?aki_policy=x_large', 3);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('543 anther Street, Pittsburgh, Pa 15222', 590.00, 1, 1, false, 'apartment', 'I am available as much or as little as needed to assist during your stay. Please do not hesitate to reach out throughout Airbnb messaging, or call my cell if time-sensitive., ', 'https://a0.muscache.com/im/pictures/prohost-api/Hosting-659419071002889120/original/3e17742a-6e4a-4338-af00-47ef54c0f409.jpeg?aki_policy=x_large', 3);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('356 outpupil Street, Pittsburgh, Pa 15212', 3450.00, 1, 2, false, 'apartment', '- Do not block other cars on premises, ', 'https://a0.muscache.com/im/pictures/miso/Hosting-619476087788915710/original/196409a2-47bc-4cc8-9b81-8ceddd838d91.jpeg?aki_policy=x_large', 3);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('204 impeachers Street, Pittsburgh, Pa 15208', 900.00, 1, 1, false, 'apartment', 'At Frontdesk, a core value is to be a good neighbor. We extend this 5-star stay to you, our guests, as well as our property partners. This means we have a zero-tolerance policy for parties or gatherings. To ensure this in the most comfortable and least intrusive way possible, we use a noise sensor to detect the noise level inside of the suite. The number of people inside the suite may not exceed the reserved guest amount at any time. While we do not anticipate the need, following multiple warnings, we will utilize local law enforcement to ensure compliance. If removal is required, it will be done at the guests expense.  Thank you for respecting the community and our commitment to be a good neighbor., ', 'https://a0.muscache.com/im/pictures/miso/Hosting-44153085/original/2c9a3727-08f2-4d8b-bdf8-d9a5939ccf14.jpeg?aki_policy=x_large', 3);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('550 pillagers Street, Pittsburgh, Pa 15207', 850.00, 1, 1, false, 'apartment', '- There is a loft in the apt (seen in pics) the ladder is steep, please keep that in mind for the 5th person sleeping., ', 'https://a0.muscache.com/im/pictures/miso/Hosting-679895630452857755/original/6c852c9e-790f-4304-9707-92352978875b.jpeg?aki_policy=x_large', 1);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('112 maybird Street, Pittsburgh, Pa 15211', 5500.00, 3.5, 3, false, 'apartment', 'easy bus access, walking distance to Bakery Square, ', 'https://a0.muscache.com/im/pictures/prohost-api/Hosting-659248574425388495/original/8f73c27b-66dc-46ad-b620-0dc6192a91bc.jpeg?aki_policy=x_large', 2);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('723 cambia Street, Pittsburgh, Pa 15203', 700.00, 1, 2, false, 'apartment', 'We have a parking spot on premises for our guests!, ', 'https://a0.muscache.com/im/pictures/miso/Hosting-13116137/original/a3651cad-a618-4763-8f54-96e858caa148.jpeg?aki_policy=x_large', 3);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('198 juridically Street, Pittsburgh, Pa 15224', 990.00, 1, 1, false, 'apartment', 'Just a short walk away from the main Grandview Avenue. Easiest way for transportation would be to drive and/or uber to other portions of the city., ', 'https://a0.muscache.com/im/pictures/miso/Hosting-40670939/original/d1bfce29-1c73-4f80-9007-03e8a01be81a.jpeg?aki_policy=x_large', 2);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('955 maumets Street, Pittsburgh, Pa 15201', 1000.00, 1, 1, false, 'apartment', 'This is a 2-bedroom apartment with new bathroom tile, vanity, and fixtures., ', 'https://a0.muscache.com/im/pictures/f8e892de-2673-4782-944a-17eac0774af1.jpg?aki_policy=x_large', 2);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('702 analphabet Street, Pittsburgh, Pa 15203', 910.00, 1, 1, false, 'apartment', 'The Hayloft is a private apartment with its own entrance. Guests MUST climb a flight of stairs to access. A stove is not available, however we have a hotplate, microwave, toaster oven, and electric kettle for your convenience., ', 'https://a0.muscache.com/im/pictures/949e0374-122e-4f9c-b636-e41266ef1ad8.jpg?aki_policy=x_large', 2);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('590 misappraisals Street, Pittsburgh, Pa 15221', 1150.00, 1, 2, false, 'apartment', 'The South Side Flats are a very walkable area., ', 'https://a0.muscache.com/im/pictures/miso/Hosting-676715070074083727/original/55225352-302d-4998-80ce-8fb9065aecfe.jpeg?aki_policy=x_large', 3);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('396 subclassified Street, Pittsburgh, Pa 15211', 1980.00, 1.5, 2, false, 'apartment', 'Stylish, relaxing space close to lots of shopping areas and restaurants.  Recently remodeled, and includes parking & backyard patio.   (We are in the process of furnishing it now.  Please check my other listings to see our furnishing style!), ', 'https://a0.muscache.com/im/pictures/miso/Hosting-666789117360564248/original/38e2195c-9509-442a-a829-17af00ad60a8.jpeg?aki_policy=x_large', 1);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('640 proctodea Street, Pittsburgh, Pa 15206', 380.00, 1, 1, false, 'apartment', 'Shaler Township is a suburb of Pittsburgh with a population of 27,862. Shaler Township is in Allegheny County and is one of the best places to live in Pennsylvania. Living in Shaler Township offers residents a sparse suburban feel and most residents own their homes, ', 'https://a0.muscache.com/im/pictures/miso/Hosting-17944234/original/4ec25eff-06ed-4d4d-9204-b4302414ffdf.jpeg?aki_policy=x_large', 3);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('976 dispenses Street, Pittsburgh, Pa 15202', 1000.00, 1, 1, false, 'apartment', 'The South Side, Strip District, Pitts Campus and Downtown are an easy drive/Uber/Cab away!, ', 'https://a0.muscache.com/im/pictures/miso/Hosting-657858112792529076/original/ddaa9e01-eed9-4785-9f2d-08392d94f245.jpeg?aki_policy=x_large', 2);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('106 originals Street, Pittsburgh, Pa 15213', 590.00, 1, 1, false, 'apartment', 'Stanton Castle is located in the vibrant East End of Pittsburgh. The private room is located in the third floor apartment. There are three locked bedrooms in the apartment, each with their own private bathrooms. The kitchen and lounge are shared with other guests like yourself., ', 'https://a0.muscache.com/im/pictures/prohost-api/Hosting-684872309065651314/original/08e57367-adf1-4c69-a37c-dcba6c8377d8.jpeg?aki_policy=x_large', 1);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('86 massacred Street, Pittsburgh, Pa 15211', 6800.00, 3, 4, false, 'apartment', 'At Frontdesk, a core value is to be a good neighbor. We extend this 5-star stay to you, our guests, as well as our property partners. This means we have a zero-tolerance policy for parties or gatherings. To ensure this in the most comfortable and least intrusive way possible, we use a noise sensor to detect the noise level inside of the suite. The number of people inside the suite may not exceed the reserved guest amount at any time. While we do not anticipate the need, following multiple warnings, we will utilize local law enforcement to ensure compliance. If removal is required, it will be done at the guests expense.  Thank you for respecting the community and our commitment to be a good neighbor., ', 'https://a0.muscache.com/im/pictures/miso/Hosting-679529237448668420/original/417db864-afef-4585-b926-99903f601aa7.jpeg?aki_policy=x_large', 4);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('174 coursing Street, Pittsburgh, Pa 15222', 590.00, 1, 1, false, 'apartment', 'This unique place has a style all its own, with quality furnishings and original artwork by local artists., ', 'https://a0.muscache.com/im/pictures/prohost-api/Hosting-646164160053795918/original/9b9316f3-8666-4f81-bec7-791a5f25a1a6.jpeg?aki_policy=x_large', 1);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('916 screamingly Street, Pittsburgh, Pa 15222', 590.00, 1, 1, false, 'apartment', 'There are no stairs leading from street level to house. There is 1 flight of stairs leading from 1st floor to 2nd floor, and 1 flight of stairs from 2nd floor to 3rd floor., ', 'https://a0.muscache.com/im/pictures/prohost-api/Hosting-645652716244039552/original/b955af58-4ea1-4d0f-baa7-de1dac82fa2d.jpeg?aki_policy=x_large', 1);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('547 toffees Street, Pittsburgh, Pa 15213', 590.00, 1, 1, false, 'apartment', 'At Frontdesk, a core value is to be a good neighbor. We extend this 5-star stay to you, our guests, as well as our property partners. This means we have a zero-tolerance policy for parties or gatherings. To ensure this in the most comfortable and least intrusive way possible, we use a noise sensor to detect the noise level inside of the suite. The number of people inside the suite may not exceed the reserved guest amount at any time. While we do not anticipate the need, following multiple warnings, we will utilize local law enforcement to ensure compliance. If removal is required, it will be done at the guests expense.  Thank you for respecting the community and our commitment to be a good neighbor., ', 'https://a0.muscache.com/im/pictures/prohost-api/Hosting-684877390932314389/original/441a4f72-448b-4b6a-9f49-04cfd1270361.jpeg?aki_policy=x_large', 3);
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord_id) VALUES ('645 choreographers Street, Pittsburgh, Pa 15224', 1000.00, 1.5, 2, false, 'apartment', 'Guest will have access to everything but closets and garage, ', 'https://a0.muscache.com/im/pictures/5b2f38fa-67e7-4371-9927-a7462fae2a0b.jpg?aki_policy=x_large', 1);


Insert Into maintenance(maintenance_request, rental_id) Values ('Roof is leaking', 1);
Insert Into maintenance(maintenance_request, rental_id) Values ('Bathtub is leaking', 14);
Insert Into maintenance(maintenance_request, rental_id) Values ('Sink is leaking', 17);
Insert Into maintenance(maintenance_request, rental_id) Values ('Something else is leaking', 5);
INSERT INTO maintenance(maintenance_request, rental_id) VALUES ('shitters full', 18);




INSERT Into user_rental (user_id, rental_id, last_paid) VALUES (5,1,(Select Current_Date - 5));
INSERT Into user_rental (user_id, rental_id, last_paid) VALUES (6,2,(Select Current_Date - 6));
INSERT Into user_rental (user_id, rental_id, last_paid) VALUES (7,14,(Select Current_Date - 7));
INSERT Into user_rental (user_id, rental_id, last_paid) VALUES (8,16,(Select Current_Date - 8));
INSERT Into user_rental (user_id, rental_id, last_paid) VALUES (9,17,(Select Current_Date - 9));
INSERT Into user_rental (user_id, rental_id, last_paid) VALUES (10,18,(Select Current_Date - 15));
INSERT Into user_rental (user_id, rental_id, last_paid) VALUES (11,5,(Select Current_Date - 25));
INSERT Into user_rental (user_id, rental_id, last_paid) VALUES (12,6, (Select Current_Date - 35));



COMMIT TRANSACTION;

