BEGIN TRANSACTION;

INSERT INTO users (username,password_hash,role) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN');

INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord) VALUES ('3837 Ackley Wy, Pittsburgh, PA 15214', 1680.00, 1.5, 2, false, 'house', 'Located in the historic north side area of Pittsburgh. This cozy 2-Bed, 1.5-Bath home is equipped with its luxurious furnishings, a full kitchen, dining room, movie theatre, Wi-Fi, parking, smart locks for your safety and much more. Treat your taste buds at the north-shore 9 minutes away from this home. That’s just a teaser, looking to dig deeper check out the overlook in the west end with sensational views of the shimmering skyline. Be sure to spend a night out on the southside for bars & clubs.', 'https://a0.muscache.com/im/pictures/miso/Hosting-649102397892688083/original/279b62ec-971a-4068-87cb-688f4103204a.jpeg?aki_policy=large', 'Tom Assword');
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord) VALUES ('2318 Jane St, Pittsburgh, PA 15203', 1950.00, 2.5, 3, false, 'house', 'Kick back and relax in this calm, stylish space. Our house has 3 bedrooms available on the second floor of the house. We have kings size bed in the master bedroom, queen size bed and full size bed in the third bedroom. A portable baby crib is available for use if needed. The house has 2 full bathrooms and 1 half bath.', 'https://a0.muscache.com/im/pictures/miso/Hosting-673696039027617516/original/fdeada62-422f-44e2-8d63-968f082f611c.png?aki_policy=large', 'Tom Assword');
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord) VALUES ('36 Enon Way, Pittsburgh, PA 15203', 910.00, 1.0, 1, false, 'apartment', 'Updated 1 bedroom apartment just a couple blocks from South Side Flats entertainment district. Close to everything, yet secluded from the hustle and bustle of Carson street, downtown, and Oakland. The bedroom includes a queen-sized bed. Wifi is included.', 'https://a0.muscache.com/im/pictures/miso/Hosting-38729034/original/413494dd-dfcb-4149-aad0-f02552e29fcc.jpeg?aki_policy=small', 'Becky Assword');
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord) VALUES ('319 Sweetbriar St, Pittsburgh, PA 15211', 1650.00, 1.0, 3, false, 'house', 'Keep it simple at this peaceful and centrally-located 3-Bedroom home. Located just one block from the famous Mt. Washington overlook, this home is conveniently located to everything Pittsburgh has to offer. Features a spacious backyard, high-speed WIFI, SmartTV, laundry facilities, memory-foam beds and plenty of FREE street parking! Close to groceries, restaurants, hiking trails, and just a short ride down the iconic Pittsburgh Incline to reach Downtown, South-Side, and Station Square.', 'https://a0.muscache.com/im/pictures/miso/Hosting-660635555742898325/original/e8d2c4d1-472d-4746-a608-37fdf1e9fb6a.jpeg?aki_policy=small', 'Becky Assword');
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord) VALUES ('209 9th St Apartment 1, Pittsburgh, PA 15222', 590.00, 0.0, 1.0, false, 'apartment', 'All Front desk stays are contactless self-check-in and include Scout, our exclusive digital companion to guide you through everything you will need before and during your time with us. We are also available 24/7 via text or phone and have a local team should you need anything.', 'https://a0.muscache.com/im/pictures/prohost-api/Hosting-645540054560482356/original/061b19ab-90f2-48e3-9cd8-8fbbe4b726ab.jpeg?aki_policy=small', 'Kim Teplitzky');
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord) VALUES ('209 9th St Apartment 2, Pittsburgh, PA 15222', 590.00, 1.0, 1.0, false, 'apartment', 'Please note, the building is currently undergoing a complete renovation, including the lobby, entrance/exit areas, common areas, hallways, etc. and there are active construction sites that guests will have to pass through during their stay.', 'https://a0.muscache.com/im/pictures/prohost-api/Hosting-659446227161633075/original/f31841f8-01f1-4522-9a2b-028f45f7d107.jpeg?aki_policy=large', 'Kim Teplitzky');
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord) VALUES ('5606 Stanton Ave Apartment 3, Pittsburgh, PA 15206', 590.00, 1.0, 1.0, false, 'aoartment', 'Anything in the apartment is yours to use. Make yourself at home once you arrive. While traditional cable TV is not included in your stay, we do provide Roku TVs with apps like Netflix, Prime, Hulu, and more! Feel free to use these services with your own login and enjoy!', 'https://a0.muscache.com/im/pictures/prohost-api/Hosting-645713686230889645/original/8dba2fe3-db8c-45a3-bbd0-db451c1b6c37.jpeg?aki_policy=large', 'Lance Lyde');
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord) VALUES ('5606 Stanton Ave Apartment 6, Pittsburgh, PA 15206', 590.00, 1.0, 1.0, false, 'aoartment', 'All Frontdesk stays are contactless self-check-in and include Scout, our exclusive digital companion to guide you through everything you will need before and during your time with us. We are also available 24/7 via text or phone and have a local team should you need anything.', 'https://a0.muscache.com/im/pictures/prohost-api/Hosting-659225921537019795/original/a4fcf0a8-d4af-4f42-a01a-be4ad13ce7af.jpeg?aki_policy=large', 'Lance Lyde');
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord) VALUES ('5606 Stanton Ave Apartment 9, Pittsburgh, PA 15206', 590.00, 1.0, 1.0, false, 'aoartment', 'Spacious Basement suite in my home with full sized bed , electric fireplace, treadmill workout area, work desk, mini microwave kitchenette, 42" flat screen TV, Wi-Fi, bathroom/ shower, laundry facilities and off street parking. Room is tastefully decorated warm, inviting and functional. Guest uses garage entrance with code, 100% privacy. Host may be on property. 8 Minutes from downtown, PNC Park, Heinz Field, Pittsburgh Paints Arena, Mt Washingtons Inclines and restaurants 15 from Airport A full sized bed and fireplace will greet you.', 'https://a0.muscache.com/im/pictures/miso/Hosting-667490516860790612/original/1e046a79-f964-434c-8a7d-16370620b247.jpeg?aki_policy=large', 'Lance Lyde');
INSERT INTO rental_property (rental_address,rental_amount,bathrooms,bedrooms,is_rented,type_of_residence, description, picture, landlord) VALUES ('5606 Stanton Ave Apartment 9, Pittsburgh, PA 15206', 590.00, 1.0, 1.0, false, 'apartment', 'Stanton Castle is located in the vibrant East End of Pittsburgh. The private room is located in the third floor apartment. There are three locked bedrooms in the apartment, each with their own private bathrooms. The kitchen and lounge are shared with other guests like yourself.','https://a0.muscache.com/im/pictures/miso/Hosting-17944234/original/4ec25eff-06ed-4d4d-9204-b4302414ffdf.jpeg?aki_policy=large', 'Lance Lyde');

COMMIT TRANSACTION;
